### PR TITLE
Ref Tasks[66650] create base project, homepage, register and login page

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Homepage
ảnh
ảnh
ảnh
ảnh
Login Page
ảnh
ảnh
Register Page
ảnh
ảnh
ảnh

**Comment by daitiennguyenptit** [comment]
card
image
checkout
image
image

**Comment by daitiennguyenptit** [comment]
confirm order
image
contact
image
image

**Comment by daitiennguyenptit** [comment]
newsdetail
image
image

**Comment by daitiennguyenptit** [comment]
new list
image

**Comment by daitiennguyenptit** [comment]
product detail
image
product grid
image
product list
image

**Pull request closed without merging**
